on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]

name: Create container image

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: nowcasting_fcst
        tags: latest
        containerfiles: ./Containerfile
    - name: Test image
      uses: fmidev/podman-run-action@v1
      with:
        image: ${{ steps.build-image.outputs.image-with-tag }}
        run: python3 /nowcasting_fcst/call_interpolation.py --help
    - name: Push to quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/fmi
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
